# AuthzPolicy (networksecurity.googleapis.com)
name: projects/wortz-project-352116/locations/us-central1/authzPolicies/ge-gateway-iap-policy
description: "Binds IAP AuthzExtension to Agent Gateway"
target:
  loadBalancingScheme: INTERNAL_MANAGED
  resources:
    - "projects/wortz-project-352116/locations/us-central1/agentGateways/ge-private-egress-gateway"
action: CUSTOM
customProvider:
  authzExtension:
    resources:
      - "projects/wortz-project-352116/locations/us-central1/authzExtensions/ge-iap-authz-ext"
policyProfile: REQUEST_AUTHZ
